### PR TITLE
Fix #419 for send-keys and run-command

### LINKED ISSUE #419: Unexpected behaviour when trying to cancel a gesture
### Describe the bug

When you start a send_keys gesture, it will go through with the action even if you reset the gesture progress to 0.

So for example, I have this in my config:
```xml
    <!-- New tab -->
    <gesture type="SWIPE" fingers="3" direction="UP">
      <action type="SEND_KEYS">
        <modifiers>Control_L</modifiers>
        <keys>T</keys>
      </action>
    </gesture>
    <!-- Close tab -->
    <gesture type="SWIPE" fingers="3" direction="DOWN">
      <action type="SEND_KEYS">
        <modifiers>Control_L</modifiers>
        <keys>W</keys>
        <repeat>false</repeat>
        <on>end</on>
      </action>
    </gesture>
```

The usual behaviour is: I swipe my three fingers down, take them off the touchpad, and a tab closes.
The unusual behaviour: I swipe my three fingers down, and while my fingers are still on the touchpad, start swiping them back up again; then when I take my fingers off the touchpad, a tab still closes.

### Expected behaviour

When moving a gestire in the opposite direction, it should be cancelled

### Actual behaviour

The gesture completes regardless of swipe direction

### Your environment

 * Version of Touchégg: v2.0.4
 * Operating System: opensuse 15.1
 * Desktop Environment: KDE 5.12.8

### PR DESCRIPTION
**Pull request by d86leader**
Partly fixes #419 

1. Notice that `send-keys` and `run-command` are very similar, abstract that into `repeated-action`
2. Make `repeated-action` respect animation threshold (even though there are no animations there)
3. Notice that `repeated-action` and `animated-action` use threshold in the same way, abstract that into `action`

Now the only action that doesn't respect threshold is `mouse-click`, but it's pretty different in usage from the others, so I'm not sure. It's used for tablets, right? What completion percentages are emitted there for gestures?

### CODE REVIEW

File: src/actions/repeated-action.h [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+  /**
+   * If your action requires some pre-setup, override this method. This is
+   * executed unconditionally upon gesture beginning
+   */
+  virtual void executePrelude();
+  /**
+   * If your action requires some post-setup, override this method. This is
+   * executed unconditionally upon gesture ending
+   */
+  virtual void executePostlude();
```
Comment (JoseExposito) [inline src/actions/repeated-action.h:50]: Should this be virtual pure?

```suggestion
  virtual void executePostlude() = 0;
```

File: src/actions/repeated-action.h [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+   */
+  virtual void executeReverse(const Gesture &gesture) = 0;
+
+ protected:
+  bool repeat = false;
+  int repeatPercentage = 0;
+  bool onBegin = true;
+  /** Safeguard against executing onBegin action multiple times when execution
+   * threshold is surpassed multiple times */
+  bool onBeginExecuted = false;
```
Comment (JoseExposito) [inline src/actions/repeated-action.h:66]: The method `onGestureBegin(const Gesture &gesture)` is guaranteed to be called once, so I think it is safe to remove this flag.

File: src/actions/repeated-action.cpp [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+  if (!this->repeat && this->onBegin) {
+    if (gesture.percentage() > this->threshold) {
+      this->executeAction(gesture);
+      this->onBeginExecuted = true;
+    }
+  }
+}
+
+void RepeatedAction::onGestureUpdate(const Gesture &gesture) {
+  if (this->onBegin && !this->onBeginExecuted) {
```
Comment (JoseExposito) [inline src/actions/repeated-action.cpp:46]: Why do you execute the `onBegin` action here again?

File: src/actions/repeated-action.cpp [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+    if (decreased) {
+      this->executeReverse(gesture);
+      this->repeatPercentage -= step;
+    }
+  }
+}
+
+void RepeatedAction::onGestureEnd(const Gesture &gesture) {
+  if (!this->repeat && !this->onBegin) {
+    if (gesture.percentage() > this->threshold) {
```
Comment (JoseExposito) [inline src/actions/repeated-action.cpp:71]: Same here, it should be `>=` to be consistent with previous versions:

```suggestion
    if (gesture.percentage() >= this->threshold) {
```

**Review by JoseExposito — CHANGES_REQUESTED** [review]
Hi! Thanks for your pull request.

It is looking good, I just left a few comments before we merge it.

File: src/actions/repeated-action.h [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+  /**
+   * Execute gesture on end if threshold passed
+   */
+  void onGestureEnd(const Gesture &gesture) override;
+
+  /**
+   * If your action requires some pre-setup, override this method. This is
+   * executed unconditionally upon gesture beginning
+   */
+  virtual void executePrelude();
```
[the remark this answers is not in the document]
Comment (d86leader) [reply src/actions/repeated-action.h:45]: Well, the code which is now in prelude for `send-keys` and `run-command` was not in constructor before. Also, for `executePrelude` the time this is called is explicitly stated, which is not true for constructors: I'm still not sure when they are called.

File: src/actions/repeated-action.h (hunk 1 above)
Comment (d86leader) [reply src/actions/repeated-action.h:50]: I don't think it should, I think prelude and postlude should be defaulted to noop for derived classes that don't need them, like `run-command` dosn't override `executePostlude` so nothing is executed there

File: src/actions/repeated-action.h (hunk 2 above)
Comment (d86leader) [reply src/actions/repeated-action.h:66]: You see, I made it so that `onGestureBegin` doesn't always execute the gesture, it only exectues it if the threshold was passed during the beginning. If the threshold wasn't passed during the beginning, we execute the action during `onGestureUpdate` the first time threshold is passed.
Now that I think about it, this is not the same behaviour as it was before. I think it might be a good idea to keep the old behaviour, but also to add this new behaviour with a new option `<on>threshold</on>`

File: src/actions/repeated-action.cpp (hunk 3 above)
Comment (d86leader) [reply src/actions/repeated-action.cpp:46]: See above, it's executed here if the threshold wasn't passed on gesture begin

File: src/actions/action.h [hunk 6]
```diff
@@ -30,6 +30,10 @@
  * Base class for all actions. Use the ActionFactory to build actions.
  */
 class Action {
+ private:
+  /** Failsafe read gesture threshold property from config */
```
[the remark this answers is not in the document]
Comment (d86leader) [reply src/actions/action.h]: Fix: a88499d08b58f95b12df3e7063176a1632621187

File: src/actions/action.h [hunk 7]
```diff
@@ -62,6 +67,9 @@ class Action {
   const WindowSystem &windowSystem;
   const WindowT &window;
   const Config &config;
+  /** Special config value: threshold to execute action. All derived actions
```
[the remark this answers is not in the document]
Comment (d86leader) [reply src/actions/action.h]: Fix: a88499d08b58f95b12df3e7063176a1632621187

File: src/actions/animated-action.cpp [hunk 8]
```diff
@@ -68,10 +68,7 @@ void AnimatedAction::onGestureUpdate(const Gesture &gesture) {
 }
 
 void AnimatedAction::onGestureEnd(const Gesture &gesture) {
-  int threshold =
-      std::stoi(this->config.getGlobalSetting("action_execute_threshold"));
-
-  if (!this->animate || gesture.percentage() >= threshold) {
+  if (!this->animate || gesture.percentage() > this->threshold) {
```
[the remark this answers is not in the document]
Comment (d86leader) [reply src/actions/animated-action.cpp]: Fix: a88499d08b58f95b12df3e7063176a1632621187

File: src/actions/repeated-action.cpp (hunk 4 above)
Comment (d86leader) [reply src/actions/repeated-action.cpp]: Fix: a88499d08b58f95b12df3e7063176a1632621187

File: src/actions/repeated-action.h (hunk 2 above)
Comment (JoseExposito) [reply src/actions/repeated-action.h:70]: Yes, when the `on` tag is set to `begin`, the action should be executed unconditionally at the beginning of the gesture so actions feel quick to perform.
I'd rather not include any extra options because the config file is already pretty complex. In addition, I'd have to add it and maintain it in the (work in progress) GUI.

File: src/actions/repeated-action.h (hunk 1 above)
Comment (JoseExposito) [reply src/actions/repeated-action.h:50]: Fair enough, I prefer it virtual pure so it is clear what methods are children classes suppose to override plus it also makes clear that `RepeatedAction` is not mean to be instantiated. But it's up to you, I'm OK with both options, feel free to resolve this conversation if you want.

File: src/actions/action.cpp [hunk 9]
```diff
@@ -0,0 +1,34 @@
...
+  try {
+    threshold =
+      std::stoi(config.getGlobalSetting("action_execute_threshold"));
+  } catch (std::exception& e) {
+    std::cout << "Bad action_execute_threshold value: "
+              << e.what() << std::endl;
+    // leave default 0 if numeric conversion failed
+  }
+  // discard negative percentage
+  return std::max(threshold, 0);
```
Comment (JoseExposito) [inline src/actions/action.cpp:33]: Thinking out loud, maybe it makes sense to `clamp` between 0 and 100 so the value is always a percentage.

**Review by JoseExposito — CHANGES_REQUESTED** [review]

File: src/actions/repeated-action.h (hunk 2 above)
Comment (d86leader) [reply src/actions/repeated-action.h]: fix: 86170b44b507cc72077c369d560298a83c57fc2b

File: src/actions/repeated-action.cpp (hunk 3 above)
Comment (d86leader) [reply src/actions/repeated-action.cpp]: fix: 86170b44b507cc72077c369d560298a83c57fc2b

File: src/actions/action.cpp (hunk 9 above)
Comment (d86leader) [reply src/actions/action.cpp]: Why not. 86170b44b507cc72077c369d560298a83c57fc2b

**Comment by JoseExposito** [comment]
Thanks for fixing this @d86leader :tada: 

There are some issues with clang-format/tidy, but I'll fix them on master, as the linter rules change a lot between versions.
